definitions:
  github_com_itera-io_openstack-web-client_api_dto.AuthenticateUserRequest:
    properties:
      applicationCredentialID:
        description: |-
          Authentication through Application Credentials requires supplying name, project and secret
          For project we can use TenantID
        type: string
      applicationCredentialName:
        type: string
      applicationCredentialSecret:
        type: string
      domain:
        type: string
      password:
        type: string
      url:
        type: string
      username:
        type: string
    required:
    - url
    type: object
  github_com_itera-io_openstack-web-client_api_dto.CommonDto:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  github_com_itera-io_openstack-web-client_api_dto.FlavorDto:
    properties:
      disk:
        description: Disk is the amount of root disk, measured in GB.
        type: integer
      id:
        description: ID is the flavor's unique ID.
        type: string
      name:
        description: Name is the name of the flavor.
        type: string
      os-flavor-access:is_public:
        description: IsPublic indicates whether the flavor is public.
        type: boolean
      ram:
        description: RAM is the amount of memory, measured in MB.
        type: integer
      vcpus:
        description: VCPUs indicates how many (virtual) CPUs are available for this
          flavor.
        type: integer
    type: object
  github_com_itera-io_openstack-web-client_api_dto.GetFlavorResponse:
    properties:
      flavor:
        items:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.FlavorDto'
        type: array
    type: object
  github_com_itera-io_openstack-web-client_api_dto.GetImageResponse:
    properties:
      image:
        items:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.ImageDto'
        type: array
    type: object
  github_com_itera-io_openstack-web-client_api_dto.ImageDto:
    properties:
      disk:
        description: Disk is the amount of root disk, measured in GB.
        type: integer
      id:
        description: ID is the flavor's unique ID.
        type: string
      name:
        description: Name is the name of the flavor.
        type: string
      ram:
        description: RAM is the amount of memory, measured in MB.
        type: integer
      status:
        description: VCPUs indicates how many (virtual) CPUs are available for this
          flavor.
        type: string
    type: object
  github_com_itera-io_openstack-web-client_api_dto.ImageListItem:
    properties:
      disk:
        description: Disk is the amount of root disk, measured in GB.
        type: integer
      id:
        description: ID is the flavor's unique ID.
        type: string
      name:
        description: Name is the name of the flavor.
        type: string
      ram:
        description: RAM is the amount of memory, measured in MB.
        type: integer
      tag:
        description: Tags filters on specific image tags.
        items:
          type: string
        type: array
    type: object
  github_com_itera-io_openstack-web-client_api_dto.ListFlavorRequest:
    properties:
      minDisk:
        type: integer
      minRam:
        type: integer
    type: object
  github_com_itera-io_openstack-web-client_api_dto.ListFlavorResponse:
    properties:
      flavors:
        items:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.FlavorDto'
        type: array
    type: object
  github_com_itera-io_openstack-web-client_api_dto.ListImageRequest:
    properties:
      owner:
        description: Owner filters on the project ID of the image.
        type: string
      status:
        description: |-
          Status filters on the status of the image.
          Multiple statuses can be specified by constructing a string
          such as "in:saving,queued,active".
        type: string
      tag:
        description: Tags filters on specific image tags.
        items:
          type: string
        type: array
    type: object
  github_com_itera-io_openstack-web-client_api_dto.ListImageResponse:
    properties:
      images:
        items:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.ImageListItem'
        type: array
    type: object
  github_com_itera-io_openstack-web-client_api_dto.ListProjectRequest:
    type: object
  github_com_itera-io_openstack-web-client_api_dto.ListProjectResponse:
    properties:
      projects:
        items:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.CommonDto'
        type: array
    type: object
  github_com_itera-io_openstack-web-client_api_dto.ListRegionRequest:
    type: object
  github_com_itera-io_openstack-web-client_api_dto.ListRegionResponse:
    properties:
      regions:
        items:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.CommonDto'
        type: array
    type: object
  github_com_itera-io_openstack-web-client_api_dto.ListUserProjectResponse:
    properties:
      projects:
        items:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.CommonDto'
        type: array
    type: object
  github_com_itera-io_openstack-web-client_api_dto.ValidateUserRequest:
    properties:
      domain:
        type: string
      password:
        minLength: 6
        type: string
      url:
        type: string
      username:
        minLength: 3
        type: string
    required:
    - password
    - url
    - username
    type: object
  github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse:
    properties:
      error: {}
      result: {}
      resultCode:
        $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.ResultCode'
      success:
        type: boolean
      validationErrors:
        items:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_validations.ValidationError'
        type: array
    type: object
  github_com_itera-io_openstack-web-client_api_helper.ResultCode:
    enum:
    - 0
    - 40001
    - 40101
    - 40301
    - 40401
    - 42901
    - 42902
    - 50001
    - 50002
    type: integer
    x-enum-varnames:
    - Success
    - ValidationError
    - AuthError
    - ForbiddenError
    - NotFoundError
    - LimiterError
    - OtpLimiterError
    - CustomRecovery
    - InternalError
  github_com_itera-io_openstack-web-client_api_validations.ValidationError:
    properties:
      message:
        type: string
      property:
        type: string
      tag:
        type: string
      value:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/health/:
    get:
      consumes:
      - application/json
      description: Health Check
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
      summary: Health Check
      tags:
      - health
  /v1/users/auth:
    post:
      consumes:
      - application/json
      description: Authenticate User
      parameters:
      - description: AuthenticateUserRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.AuthenticateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
      summary: Authenticate User
      tags:
      - Users
  /v1/users/validate:
    post:
      consumes:
      - application/json
      description: Validate User
      parameters:
      - description: ValidateUserRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.ValidateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
      summary: Validate User
      tags:
      - Users
  /v2/flavors:
    get:
      consumes:
      - application/json
      description: List Flavor
      parameters:
      - description: ListFlavor Request
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.ListFlavorRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ListFlavor response
          schema:
            allOf:
            - $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.ListFlavorResponse'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
        "401":
          description: Unauthorized request
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: List Flavor
      tags:
      - Flavors
  /v2/flavors/{id}:
    get:
      consumes:
      - application/json
      description: Get Flavor by ID
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: GetFlavor response
          schema:
            allOf:
            - $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.GetFlavorResponse'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
        "401":
          description: Unauthorized request
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: Get Flavor
      tags:
      - Flavors
  /v2/images:
    get:
      consumes:
      - application/json
      description: List Image
      parameters:
      - description: ListImage Request
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.ListImageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ListImage response
          schema:
            allOf:
            - $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.ListImageResponse'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
        "401":
          description: Unauthorized request
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: List Image
      tags:
      - Images
  /v2/images/{id}:
    get:
      consumes:
      - application/json
      description: Get Image by ID
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: GetImage response
          schema:
            allOf:
            - $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.GetImageResponse'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
        "401":
          description: Unauthorized request
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: Get Image
      tags:
      - Images
  /v3/Projects:
    get:
      consumes:
      - application/json
      description: List Project
      parameters:
      - description: ListProjectRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.ListProjectRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ListProject response
          schema:
            allOf:
            - $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.ListProjectResponse'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
        "401":
          description: Unauthorized request
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: List Project
      tags:
      - Projects
  /v3/regions:
    get:
      consumes:
      - application/json
      description: List Region
      parameters:
      - description: ListRegionRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.ListRegionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ListRegion response
          schema:
            allOf:
            - $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.ListRegionResponse'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
        "401":
          description: Unauthorized request
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: List Region
      tags:
      - Regions
  /v3/users/{id}/projects:
    get:
      consumes:
      - application/json
      description: List UserProject
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ListUserProject response
          schema:
            allOf:
            - $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.ListUserProjectResponse'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
        "401":
          description: Unauthorized request
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: List UserProject
      tags:
      - UserProjects
swagger: "2.0"
