definitions:
  github_com_itera-io_openstack-web-client_api_dto.AuthenticateUserRequest:
    properties:
      domain:
        type: string
      password:
        minLength: 6
        type: string
      url:
        type: string
      username:
        minLength: 3
        type: string
    required:
    - password
    - url
    - username
    type: object
  github_com_itera-io_openstack-web-client_api_dto.ListProjectRequest:
    type: object
  github_com_itera-io_openstack-web-client_api_dto.ListProjectResponse:
    properties:
      projects:
        items:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.Project'
        type: array
    type: object
  github_com_itera-io_openstack-web-client_api_dto.ListRegionRequest:
    type: object
  github_com_itera-io_openstack-web-client_api_dto.ListRegionResponse:
    properties:
      regions:
        items:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.RegionItem'
        type: array
    type: object
  github_com_itera-io_openstack-web-client_api_dto.ListUserProjectRequest:
    type: object
  github_com_itera-io_openstack-web-client_api_dto.ListUserProjectResponse:
    properties:
      projects:
        items:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.UserProject'
        type: array
    type: object
  github_com_itera-io_openstack-web-client_api_dto.Project:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  github_com_itera-io_openstack-web-client_api_dto.RegionItem:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  github_com_itera-io_openstack-web-client_api_dto.UserProject:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  github_com_itera-io_openstack-web-client_api_dto.ValidateUserRequest:
    properties:
      domain:
        type: string
      password:
        minLength: 6
        type: string
      url:
        type: string
      username:
        minLength: 3
        type: string
    required:
    - password
    - url
    - username
    type: object
  github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse:
    properties:
      error: {}
      result: {}
      resultCode:
        $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.ResultCode'
      success:
        type: boolean
      validationErrors:
        items:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_validations.ValidationError'
        type: array
    type: object
  github_com_itera-io_openstack-web-client_api_helper.ResultCode:
    enum:
    - 0
    - 40001
    - 40101
    - 40301
    - 40401
    - 42901
    - 42902
    - 50001
    - 50002
    type: integer
    x-enum-varnames:
    - Success
    - ValidationError
    - AuthError
    - ForbiddenError
    - NotFoundError
    - LimiterError
    - OtpLimiterError
    - CustomRecovery
    - InternalError
  github_com_itera-io_openstack-web-client_api_validations.ValidationError:
    properties:
      message:
        type: string
      property:
        type: string
      tag:
        type: string
      value:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/health/:
    get:
      consumes:
      - application/json
      description: Health Check
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
      summary: Health Check
      tags:
      - health
  /v1/users/auth:
    post:
      consumes:
      - application/json
      description: Authenticate User
      parameters:
      - description: AuthenticateUserRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.AuthenticateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
      summary: Authenticate User
      tags:
      - Users
  /v1/users/validate:
    post:
      consumes:
      - application/json
      description: Validate User
      parameters:
      - description: ValidateUserRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.ValidateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
      summary: Validate User
      tags:
      - Users
  /v3/Projects:
    get:
      consumes:
      - application/json
      description: List Project
      parameters:
      - description: ListProjectRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.ListProjectRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ListProject response
          schema:
            allOf:
            - $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.ListProjectResponse'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
        "401":
          description: Unauthorized request
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: List Project
      tags:
      - Projects
  /v3/regions:
    get:
      consumes:
      - application/json
      description: List Region
      parameters:
      - description: ListRegionRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.ListRegionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ListRegion response
          schema:
            allOf:
            - $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.ListRegionResponse'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
        "401":
          description: Unauthorized request
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: List Region
      tags:
      - Regions
  /v3/users/:id/projects:
    get:
      consumes:
      - application/json
      description: List UserProject
      parameters:
      - description: ListUserProjectRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.ListUserProjectRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ListUserProject response
          schema:
            allOf:
            - $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.ListUserProjectResponse'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
        "401":
          description: Unauthorized request
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: List UserProject
      tags:
      - UserProjects
swagger: "2.0"
