definitions:
  github_com_itera-io_openstack-web-client_api_dto.ValidateUserRequest:
    properties:
      applicationCredEnabled:
        type: boolean
      domain:
        type: string
      password:
        minLength: 6
        type: string
      url:
        type: string
      username:
        minLength: 3
        type: string
    required:
    - password
    - url
    - username
    type: object
  github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse:
    properties:
      error: {}
      result: {}
      resultCode:
        $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.ResultCode'
      success:
        type: boolean
      validationErrors:
        items:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_validations.ValidationError'
        type: array
    type: object
  github_com_itera-io_openstack-web-client_api_helper.ResultCode:
    enum:
    - 0
    - 40001
    - 40101
    - 40301
    - 40401
    - 42901
    - 42902
    - 50001
    - 50002
    type: integer
    x-enum-varnames:
    - Success
    - ValidationError
    - AuthError
    - ForbiddenError
    - NotFoundError
    - LimiterError
    - OtpLimiterError
    - CustomRecovery
    - InternalError
  github_com_itera-io_openstack-web-client_api_validations.ValidationError:
    properties:
      message:
        type: string
      property:
        type: string
      tag:
        type: string
      value:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/health/:
    get:
      consumes:
      - application/json
      description: Health Check
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
      summary: Health Check
      tags:
      - health
  /v1/users/validate:
    post:
      consumes:
      - application/json
      description: Validate User
      parameters:
      - description: ValidateUserRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_dto.ValidateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_itera-io_openstack-web-client_api_helper.BaseHttpResponse'
      summary: Validate User
      tags:
      - Users
swagger: "2.0"
